openapi: 3.0.1
info:
  title: Rapid Downloader Engine API
  description: Multiple API endpoints to work with Rapid Downloader engine. The API endpoints is meant to be run on localhost, because this is an offline app that uses HTTP as the IPC
  version: '0.1'
servers:
  - url: http://localhost:8888
paths:
  /{client}/download/{id}:
    parameters:
      - in: path
        name: client
        schema:
          type: string
        required: true
        description: Your client id
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: File entry id
    get:
      tags: 
        - Downloader
      description: Start the download of a file entry by id
      responses:
        '200':
          description: Successfuly start the download process
        '404':
          description: File entry is not in memory
        '500':
          description: Internal server error
  /{client}/restart/{id}:
    parameters:
      - in: path
        name: client
        schema:
          type: string
        required: true
        description: Your client id
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: File entry id
    put:
      tags: 
        - Downloader
      description: Restart the download of a file entry by id
      responses:
        '200':
          description: Successfuly start the download process
        '404':
          description: File entry is not in memory
        '500':
          description: Internal server error
  /{client}/resume/{id}:
    parameters:
      - in: path
        name: client
        schema:
          type: string
        required: true
        description: Your client id
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: File entry id
    put:
      tags: 
        - Downloader
      description: Resume the download of a file entry by id
      responses:
        '200':
          description: Successfuly start the download process
        '404':
          description: File entry is not in memory
        '500':
          description: Internal server error
  /pause/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: File entry id
    put:
      tags: 
        - Downloader
      description: Pause the download of a file entry by id
      responses:
        '200':
          description: Successfuly start the download process
        '404':
          description: File entry is not in memory
        '500':
          description: Internal server error
  /stop/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: File entry id
    put:
      tags: 
        - Downloader
      description: Stop the download of a file entry by id
      responses:
        '200':
          description: Successfuly start the download process
        '404':
          description: File entry is not in memory
        '500':
          description: Internal server error
  /ws/{client}:
    parameters:
      - in: path
        name: client
        schema:
          type: string
        required: true
        description: Your client id
    get:
      tags: 
        - Downloader
      description: Listen to progress bar of download process for each chunks
      responses:
        '101':
          description: Successfuly upgrade the connection to websocket connection
  /fetch:
    post:
      tags:
        - Entry
      description: Fetch a file entry from a given request
      requestBody:
        description: Request to fetch a file
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
            example:
              { url: 'https://link.testfile.org/PDF50MB' }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Download'
              example:
                { 
                  id: 'laAq2LJD21',
                  name: '50MB-TESTFILE.ORG.pdf',
                  url: 'https://link.testfile.org/PDF50MB',
                  provider: 'default',
                  size: 53528491,
                  type: 'Document',
                  chunklen: 5,
                  resumable: true,
                  progres: 0,
                  expired: false,
                  downloadedChunks: [0,0,0,0,0],
                  timeLeft: 0,
                  speed: 0,
                  status: 'Queued',
                  date: '2023-12-21 23:09:23.049130358 +0700 WIB m=+150.406718054'
                }
  /entries/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: File entry id
    get:
      tags:
        - Entry
      description: Get file entry detail
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Download'
              example:
                { 
                  id: 'laAq2LJD21',
                  name: '50MB-TESTFILE.ORG.pdf',
                  url: 'https://link.testfile.org/PDF50MB',
                  provider: 'default',
                  size: 53528491,
                  type: 'Document',
                  chunklen: 5,
                  resumable: true,
                  progres: 0,
                  expired: false,
                  downloadedChunks: [0,0,0,0,0],
                  timeLeft: 0,
                  speed: 0,
                  status: 'Queued',
                  date: '2023-12-21 23:09:23.049130358 +0700 WIB m=+150.406718054'
                }
  /entries:
    get:
      tags:
        - Entry
      description: Get file entry detail
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Download'
              example:
                [
                  { 
                    id: 'laAq2LJD21',
                    name: '50MB-TESTFILE.ORG.pdf',
                    url: 'https://link.testfile.org/PDF50MB',
                    provider: 'default',
                    size: 53528491,
                    type: 'Document',
                    chunklen: 5,
                    resumable: true,
                    progres: 0,
                    expired: false,
                    downloadedChunks: [0,0,0,0,0],
                    timeLeft: 0,
                    speed: 0,
                    status: 'Queued',
                    date: '2023-12-21 23:09:23.049130358 +0700 WIB m=+150.406718054'
                  }
                ]
      
  
components:
  schemas:
    Request:
      type: object
      required:
        - url
      properties:
        url: 
          type: string
        provider: 
          type: string
          default: "default"
          nullable: true
        mimeType: 
          type: string
          nullable: true
          description: File mime type such as video/mp4
        userAgent: 
          type: string
          nullable: true
        cookies:
          type: array
          items:
            $ref: '#/components/schemas/Cookie'
            
    Cookie:
      type: object
      properties:
        name: 
          type: string
        value: 
          type: string
        path: 
          type: string
        domain: 
          type: string
        expirationDate:
          type: string
          format: date
        secure:
          type: boolean
        httpOnly:
          type: boolean
        sameSite:
          type: number
          description: An enum of same site value. Default = 0, Lax = 1, Strict = 2, None = 3
        
    Download:
      type: object
      properties:
        id: 
          type: string
        name: 
          type: string
        url: 
          type: string
        provider: 
          type: string
        size: 
          type: number
          format: int64
          description: File size in int64
        type:
          type: string
          description: File type that is one of Audio, Video, Image, Compressed, Document
        chunklen:
          type: number
        resumable:
          type: boolean
        progress:
          type: number
          description: Downloaded bytes in percent
        expired:
          type: boolean
          description: Tells that a link is already expired or not
        downloadedChunks:
          type: array
          items:
            type: number
            format: int64
          description: Downloaded bytes for each chunks
        timeLeft:
          type: number
          description: Remaining time for a download to complete
        speed:
          type: number
          format: float64
          description: Download speed
        status:
          type: string
          description: Download status that is one of Queued, Downloading, Paused, Stoped, Downloaded
        date:
          type: string
          format: date